version: "3.7"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_LISTENERS=PLAINTEXT://:9092
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper
    sql:
        image: cwiersema/library-sql:final
        ports:
            - 1433:1433
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    reservationprocessor:
        image: cwiersema/reservationprocessor:latest
        environment: 
          - kafka:bootstrapservers=kafka:9092
          - kafka:groupid=reservations-consumer
          - kafka:enableautocommit=true
          - kafka:securityprotocol=0
          - kafka:autooffsetreset=0
          - kafka:http://api:3000/
    api:
      image: cwiersema/libraryapi:latest
      ports: 
        - 5000:80
      environment: 
        - ConnectionStrings__library=server=sql;database=books_prod;user=sa;password=TokyoJoe138!
        - ConnectionStrings__redis=redis
        - message=Hi
        - kafka:bootstrapservers=kafka:9092